name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  hetu_std:
    path: ../
  hetu_script: ^0.4.2+1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - packages/hetu_std/assets/bytecode/std.out